export function worldCountry(data){
    const worldCountryCluesData = [
        {country:"阿富汗",name:"Afghanistan",value:0},
        {country:"安哥拉",name:"Angola",value:0},
        {country:"阿尔巴尼亚",name:"Albania",value:0},
        {country:"阿联酋",name:"United Arab Emirates",value:0},
        {country:"阿根廷",name:"Argentina",value:0},
        {country:"亚美尼亚",name:"Armenia",value:0},
        {country:"法属南半球和南极领地",name:"French Southern and Antarctic Lands",value:0},
        {country:"澳大利亚",name:"Australia",value:0},
        {country:"奥地利",name:"Austria",value:0},
        {country:"阿塞拜疆",name:"Azerbaijan",value:0},
        {country:"布隆迪",name:"Burundi",value:0},
        {country:"比利时",name:"Belgium",value:0},
        {country:"贝宁",name:"Benin",value:0},
        {country:"布基纳法索",name:"Burkina Faso",value:0},
        {country:"孟加拉国",name:"Bangladesh",value:0},
        {country:"保加利亚",name:"Bulgaria",value:0},
        {country:"巴哈马",name:"The Bahamas",value:0},
        {country:"波斯尼亚和黑塞哥维那",name:"Bosnia and Herzegovina",value:0},
        {country:"白俄罗斯",name:"Belarus",value:0},
        {country:"伯利兹",name:"Belize",value:0},
        {country:"百慕大",name:"Bermuda",value:0},
        {country:"玻利维亚",name:"Bolivia",value:0},
        {country:"巴西",name:"Brazil",value:0},
        {country:"文莱",name:"Brunei",value:0},
        {country:"不丹",name:"Bhutan",value:0},
        {country:"博茨瓦纳",name:"Botswana",value:0},
        {country:"中非",name:"Central African Republic",value:0},
        {country:"加拿大",name:"Canada",value:0},
        {country:"瑞士",name:"Switzerland",value:0},
        {country:"智利",name:"Chile",value:0},
        {country:"中国",name:"China",value:0},
        {country:"象牙海岸",name:"Ivory Coast",value:0},
        {country:"喀麦隆",name:"Cameroon",value:0},
        {country:"刚果民主共和国",name:"Democratic Republic of the Congo",value:0},
        {country:"刚果",name:"Republic of the Congo",value:0},
        {country:"哥伦比亚",name:"Colombia",value:0},
        {country:"哥斯达黎加",name:"Costa Rica",value:0},
        {country:"古巴",name:"Cuba",value:0},
        {country:"北塞浦路斯",name:"Northern Cyprus",value:0},
        {country:"塞浦路斯",name:"Cyprus",value:0},
        {country:"捷克",name:"Czech Republic",value:0},
        {country:"德国",name:"Germany",value:0},
        {country:"吉布提",name:"Djibouti",value:0},
        {country:"丹麦",name:"Denmark",value:0},
        {country:"多米尼加",name:"Dominican Republic",value:0},
        {country:"阿尔及利亚",name:"Algeria",value:0},
        {country:"厄瓜多尔",name:"Ecuador",value:0},
        {country:"埃及",name:"Egypt",value:0},
        {country:"厄立特里亚",name:"Eritrea",value:0},
        {country:"西班牙",name:"Spain",value:0},
        {country:"爱沙尼亚",name:"Estonia",value:0},
        {country:"埃塞俄比亚",name:"Ethiopia",value:0},
        {country:"芬兰",name:"Finland",value:0},
        {country:"斐济",name:"Fiji",value:0},
        {country:"福克兰群岛",name:"Falkland Islands",value:0},
        {country:"法国",name:"France",value:0},
        {country:"加蓬",name:"Gabon",value:0},
        {country:"英国",name:"United Kingdom",value:0},
        {country:"格鲁吉亚",name:"Georgia",value:0},
        {country:"加纳",name:"Ghana",value:0},
        {country:"几内亚",name:"Guinea",value:0},
        {country:"冈比亚",name:"Gambia",value:0},
        {country:"几内亚比绍",name:"Guinea Bissau",value:0},
        {country:"赤道几内亚",name:"Equatorial Guinea",value:0},
        {country:"希腊",name:"Greece",value:0},
        {country:"格陵兰",name:"Greenland",value:0},
        {country:"危地马拉",name:"Guatemala",value:0},
        {country:"法属圭亚那",name:"French Guiana",value:0},
        {country:"圭亚那",name:"Guyana",value:0},
        {country:"洪都拉斯",name:"Honduras",value:0},
        {country:"克罗地亚",name:"Croatia",value:0},
        {country:"海地",name:"Haiti",value:0},
        {country:"匈牙利",name:"Hungary",value:0},
        {country:"印度尼西亚",name:"Indonesia",value:0},
        {country:"印度",name:"India",value:0},
        {country:"爱尔兰",name:"Ireland",value:0},
        {country:"伊朗",name:"Iran",value:0},
        {country:"伊拉克",name:"Iraq",value:0},
        {country:"冰岛",name:"Iceland",value:0},
        {country:"以色列",name:"Israel",value:0},
        {country:"意大利",name:"Italy",value:0},
        {country:"牙买加",name:"Jamaica",value:0},
        {country:"约旦",name:"Jordan",value:0},
        {country:"日本",name:"Japan",value:0},
        {country:"哈萨克斯坦",name:"Kazakhstan",value:0},
        {country:"肯尼亚",name:"Kenya",value:0},
        {country:"吉尔吉斯斯坦",name:"Kyrgyzstan",value:0},
        {country:"柬埔寨",name:"Cambodia",value:0},
        {country:"韩国",name:"South Korea",value:0},
        {country:"科索沃",name:"Kosovo",value:0},
        {country:"科威特",name:"Kuwait",value:0},
        {country:"老挝",name:"Laos",value:0},
        {country:"黎巴嫩",name:"Lebanon",value:0},
        {country:"利比里亚",name:"Liberia",value:0},
        {country:"利比亚",name:"Libya",value:0},
        {country:"斯里兰卡",name:"Sri Lanka",value:0},
        {country:"莱索托",name:"Lesotho",value:0},
        {country:"立陶宛",name:"Lithuania",value:0},
        {country:"卢森堡",name:"Luxembourg",value:0},
        {country:"拉脱维亚",name:"Latvia",value:0},
        {country:"摩洛哥",name:"Morocco",value:0},
        {country:"摩尔多瓦",name:"Moldova",value:0},
        {country:"马达加斯加",name:"Madagascar",value:0},
        {country:"墨西哥",name:"Mexico",value:0},
        {country:"马其顿",name:"Macedonia",value:0},
        {country:"马里",name:"Mali",value:0},
        {country:"缅甸",name:"Myanmar",value:0},
        {country:"黑山",name:"Montenegro",value:0},
        {country:"蒙古",name:"Mongolia",value:0},
        {country:"莫桑比克",name:"Mozambique",value:0},
        {country:"毛里塔尼亚",name:"Mauritania",value:0},
        {country:"马拉维",name:"Malawi",value:0},
        {country:"马来西亚",name:"Malaysia",value:0},
        {country:"纳米比亚",name:"Namibia",value:0},
        {country:"新喀里多尼亚",name:"New Caledonia",value:0},
        {country:"尼日尔",name:"Niger",value:0},
        {country:"尼日利亚",name:"Nigeria",value:0},
        {country:"尼加拉瓜",name:"Nicaragua",value:0},
        {country:"荷兰",name:"Netherlands",value:0},
        {country:"挪威",name:"Norway",value:0},
        {country:"尼泊尔",name:"Nepal",value:0},
        {country:"新西兰",name:"New Zealand",value:0},
        {country:"阿曼",name:"Oman",value:0},
        {country:"巴基斯坦",name:"Pakistan",value:0},
        {country:"巴拿马",name:"Panama",value:0},
        {country:"秘鲁",name:"Peru",value:0},
        {country:"菲律宾",name:"Philippines",value:0},
        {country:"巴布亚新几内亚",name:"Papua New Guinea",value:0},
        {country:"波兰",name:"Poland",value:0},
        {country:"波多黎各",name:"Puerto Rico",value:0},
        {country:"朝鲜",name:"North Korea",value:0},
        {country:"葡萄牙",name:"Portugal",value:0},
        {country:"巴拉圭",name:"Paraguay",value:0},
        {country:"卡塔尔",name:"Qatar",value:0},
        {country:"罗马尼亚",name:"Romania",value:0},
        {country:"俄罗斯",name:"Russia",value:0},
        {country:"卢旺达",name:"Rwanda",value:0},
        {country:"西撒哈拉",name:"Western Sahara",value:0},
        {country:"沙特阿拉伯",name:"Saudi Arabia",value:0},
        {country:"苏丹",name:"Sudan",value:0},
        {country:"南苏丹",name:"South Sudan",value:0},
        {country:"塞内加尔",name:"Senegal",value:0},
        {country:"所罗门群岛",name:"Solomon Islands",value:0},
        {country:"塞拉利昂",name:"Sierra Leone",value:0},
        {country:"萨尔瓦多",name:"El Salvador",value:0},
        {country:"索马里兰",name:"Somaliland",value:0},
        {country:"索马里",name:"Somalia",value:0},
        {country:"塞尔维亚",name:"Republic of Serbia",value:0},
        {country:"苏里南",name:"Suriname",value:0},
        {country:"斯洛伐克",name:"Slovakia",value:0},
        {country:"斯洛文尼亚",name:"Slovenia",value:0},
        {country:"瑞典",name:"Sweden",value:0},
        {country:"斯威士兰",name:"Swaziland",value:0},
        {country:"叙利亚",name:"Syria",value:0},
        {country:"乍得",name:"Chad",value:0},
        {country:"多哥",name:"Togo",value:0},
        {country:"泰国",name:"Thailand",value:0},
        {country:"塔吉克斯坦",name:"Tajikistan",value:0},
        {country:"土库曼斯坦",name:"Turkmenistan",value:0},
        {country:"东帝汶",name:"East Timor",value:0},
        {country:"特里尼达和多巴哥",name:"Trinidad and Tobago",value:0},
        {country:"突尼斯",name:"Tunisia",value:0},
        {country:"土耳其",name:"Turkey",value:0},
        {country:"坦桑尼亚",name:"United Republic of Tanzania",value:0},
        {country:"乌干达",name:"Uganda",value:0},
        {country:"乌克兰",name:"Ukraine",value:0},
        {country:"乌拉圭",name:"Uruguay",value:0},
        {country:"美国",name:"United States of America",value:0},
        {country:"乌兹别克斯坦",name:"Uzbekistan",value:0},
        {country:"委内瑞拉",name:"Venezuela",value:0},
        {country:"越南",name:"Vietnam",value:0},
        {country:"瓦努阿图",name:"Vanuatu",value:0},
        {country:"西岸",name:"West Bank",value:0},
        {country:"也门",name:"Yemen",value:0},
        {country:"南非",name:"South Africa",value:0},
        {country:"赞比亚",name:"Zambia",value:0},
        {country:"津巴布韦",name:"Zimbabwe",value:0},
    ];
    worldCountryCluesData.forEach(function(item,index){
        data.forEach(function(item1,index1){
            if(item.country == item1.country){
                item.value = item1.number;
            }
        });
    });
    return worldCountryCluesData;
}
