export function worldCountry(data){
    const worldCountryCluesData = [
        {name:"阿富汗",country:"Afghanistan",number:0},
        {name:"安哥拉",country:"Angola",number:0},
        {name:"阿尔巴尼亚",country:"Albania",number:0},
        {name:"阿联酋",country:"United Arab Emirates",number:0},
        {name:"阿根廷",country:"Argentina",number:0},
        {name:"亚美尼亚",country:"Armenia",number:0},
        {name:"法属南半球和南极领地",country:"French Southern and Antarctic Lands",number:0},
        {name:"澳大利亚",country:"Australia",number:0},
        {name:"奥地利",country:"Austria",number:0},
        {name:"阿塞拜疆",country:"Azerbaijan",number:0},
        {name:"布隆迪",country:"Burundi",number:0},
        {name:"比利时",country:"Belgium",number:0},
        {name:"贝宁",country:"Benin",number:0},
        {name:"布基纳法索",country:"Burkina Faso",number:0},
        {name:"孟加拉国",country:"Bangladesh",number:0},
        {name:"保加利亚",country:"Bulgaria",number:0},
        {name:"巴哈马",country:"The Bahamas",number:0},
        {name:"波斯尼亚和黑塞哥维那",country:"Bosnia and Herzegovina",number:0},
        {name:"白俄罗斯",country:"Belarus",number:0},
        {name:"伯利兹",country:"Belize",number:0},
        {name:"百慕大",country:"Bermuda",number:0},
        {name:"玻利维亚",country:"Bolivia",number:0},
        {name:"巴西",country:"Brazil",number:0},
        {name:"文莱",country:"Brunei",number:0},
        {name:"不丹",country:"Bhutan",number:0},
        {name:"博茨瓦纳",country:"Botswana",number:0},
        {name:"中非",country:"Central African Republic",number:0},
        {name:"加拿大",country:"Canada",number:0},
        {name:"瑞士",country:"Switzerland",number:0},
        {name:"智利",country:"Chile",number:0},
        {name:"中国",country:"China",number:0},
        {name:"象牙海岸",country:"Ivory Coast",number:0},
        {name:"喀麦隆",country:"Cameroon",number:0},
        {name:"刚果民主共和国",country:"Democratic Republic of the Congo",number:0},
        {name:"刚果",country:"Republic of the Congo",number:0},
        {name:"哥伦比亚",country:"Colombia",number:0},
        {name:"哥斯达黎加",country:"Costa Rica",number:0},
        {name:"古巴",country:"Cuba",number:0},
        {name:"北塞浦路斯",country:"Northern Cyprus",number:0},
        {name:"塞浦路斯",country:"Cyprus",number:0},
        {name:"捷克",country:"Czech Republic",number:0},
        {name:"德国",country:"Germany",number:0},
        {name:"吉布提",country:"Djibouti",number:0},
        {name:"丹麦",country:"Denmark",number:0},
        {name:"多米尼加",country:"Dominican Republic",number:0},
        {name:"阿尔及利亚",country:"Algeria",number:0},
        {name:"厄瓜多尔",country:"Ecuador",number:0},
        {name:"埃及",country:"Egypt",number:0},
        {name:"厄立特里亚",country:"Eritrea",number:0},
        {name:"西班牙",country:"Spain",number:0},
        {name:"爱沙尼亚",country:"Estonia",number:0},
        {name:"埃塞俄比亚",country:"Ethiopia",number:0},
        {name:"芬兰",country:"Finland",number:0},
        {name:"斐济",country:"Fiji",number:0},
        {name:"福克兰群岛",country:"Falkland Islands",number:0},
        {name:"法国",country:"France",number:0},
        {name:"加蓬",country:"Gabon",number:0},
        {name:"英国",country:"United Kingdom",number:0},
        {name:"格鲁吉亚",country:"Georgia",number:0},
        {name:"加纳",country:"Ghana",number:0},
        {name:"几内亚",country:"Guinea",number:0},
        {name:"冈比亚",country:"Gambia",number:0},
        {name:"几内亚比绍",country:"Guinea Bissau",number:0},
        {name:"赤道几内亚",country:"Equatorial Guinea",number:0},
        {name:"希腊",country:"Greece",number:0},
        {name:"格陵兰",country:"Greenland",number:0},
        {name:"危地马拉",country:"Guatemala",number:0},
        {name:"法属圭亚那",country:"French Guiana",number:0},
        {name:"圭亚那",country:"Guyana",number:0},
        {name:"洪都拉斯",country:"Honduras",number:0},
        {name:"克罗地亚",country:"Croatia",number:0},
        {name:"海地",country:"Haiti",number:0},
        {name:"匈牙利",country:"Hungary",number:0},
        {name:"印度尼西亚",country:"Indonesia",number:0},
        {name:"印度",country:"India",number:0},
        {name:"爱尔兰",country:"Ireland",number:0},
        {name:"伊朗",country:"Iran",number:0},
        {name:"伊拉克",country:"Iraq",number:0},
        {name:"冰岛",country:"Iceland",number:0},
        {name:"以色列",country:"Israel",number:0},
        {name:"意大利",country:"Italy",number:0},
        {name:"牙买加",country:"Jamaica",number:0},
        {name:"约旦",country:"Jordan",number:0},
        {name:"日本",country:"Japan",number:0},
        {name:"哈萨克斯坦",country:"Kazakhstan",number:0},
        {name:"肯尼亚",country:"Kenya",number:0},
        {name:"吉尔吉斯斯坦",country:"Kyrgyzstan",number:0},
        {name:"柬埔寨",country:"Cambodia",number:0},
        {name:"韩国",country:"South Korea",number:0},
        {name:"科索沃",country:"Kosovo",number:0},
        {name:"科威特",country:"Kuwait",number:0},
        {name:"老挝",country:"Laos",number:0},
        {name:"黎巴嫩",country:"Lebanon",number:0},
        {name:"利比里亚",country:"Liberia",number:0},
        {name:"利比亚",country:"Libya",number:0},
        {name:"斯里兰卡",country:"Sri Lanka",number:0},
        {name:"莱索托",country:"Lesotho",number:0},
        {name:"立陶宛",country:"Lithuania",number:0},
        {name:"卢森堡",country:"Luxembourg",number:0},
        {name:"拉脱维亚",country:"Latvia",number:0},
        {name:"摩洛哥",country:"Morocco",number:0},
        {name:"摩尔多瓦",country:"Moldova",number:0},
        {name:"马达加斯加",country:"Madagascar",number:0},
        {name:"墨西哥",country:"Mexico",number:0},
        {name:"马其顿",country:"Macedonia",number:0},
        {name:"马里",country:"Mali",number:0},
        {name:"缅甸",country:"Myanmar",number:0},
        {name:"黑山",country:"Montenegro",number:0},
        {name:"蒙古",country:"Mongolia",number:0},
        {name:"莫桑比克",country:"Mozambique",number:0},
        {name:"毛里塔尼亚",country:"Mauritania",number:0},
        {name:"马拉维",country:"Malawi",number:0},
        {name:"马来西亚",country:"Malaysia",number:0},
        {name:"纳米比亚",country:"Namibia",number:0},
        {name:"新喀里多尼亚",country:"New Caledonia",number:0},
        {name:"尼日尔",country:"Niger",number:0},
        {name:"尼日利亚",country:"Nigeria",number:0},
        {name:"尼加拉瓜",country:"Nicaragua",number:0},
        {name:"荷兰",country:"Netherlands",number:0},
        {name:"挪威",country:"Norway",number:0},
        {name:"尼泊尔",country:"Nepal",number:0},
        {name:"新西兰",country:"New Zealand",number:0},
        {name:"阿曼",country:"Oman",number:0},
        {name:"巴基斯坦",country:"Pakistan",number:0},
        {name:"巴拿马",country:"Panama",number:0},
        {name:"秘鲁",country:"Peru",number:0},
        {name:"菲律宾",country:"Philippines",number:0},
        {name:"巴布亚新几内亚",country:"Papua New Guinea",number:0},
        {name:"波兰",country:"Poland",number:0},
        {name:"波多黎各",country:"Puerto Rico",number:0},
        {name:"朝鲜",country:"North Korea",number:0},
        {name:"葡萄牙",country:"Portugal",number:0},
        {name:"巴拉圭",country:"Paraguay",number:0},
        {name:"卡塔尔",country:"Qatar",number:0},
        {name:"罗马尼亚",country:"Romania",number:0},
        {name:"俄罗斯",country:"Russia",number:0},
        {name:"卢旺达",country:"Rwanda",number:0},
        {name:"西撒哈拉",country:"Western Sahara",number:0},
        {name:"沙特阿拉伯",country:"Saudi Arabia",number:0},
        {name:"苏丹",country:"Sudan",number:0},
        {name:"南苏丹",country:"South Sudan",number:0},
        {name:"塞内加尔",country:"Senegal",number:0},
        {name:"所罗门群岛",country:"Solomon Islands",number:0},
        {name:"塞拉利昂",country:"Sierra Leone",number:0},
        {name:"萨尔瓦多",country:"El Salvador",number:0},
        {name:"索马里兰",country:"Somaliland",number:0},
        {name:"索马里",country:"Somalia",number:0},
        {name:"塞尔维亚",country:"Republic of Serbia",number:0},
        {name:"苏里南",country:"Suricountry",number:0},
        {name:"斯洛伐克",country:"Slovakia",number:0},
        {name:"斯洛文尼亚",country:"Slovenia",number:0},
        {name:"瑞典",country:"Sweden",number:0},
        {name:"斯威士兰",country:"Swaziland",number:0},
        {name:"叙利亚",country:"Syria",number:0},
        {name:"乍得",country:"Chad",number:0},
        {name:"多哥",country:"Togo",number:0},
        {name:"泰国",country:"Thailand",number:0},
        {name:"塔吉克斯坦",country:"Tajikistan",number:0},
        {name:"土库曼斯坦",country:"Turkmenistan",number:0},
        {name:"东帝汶",country:"East Timor",number:0},
        {name:"特里尼达和多巴哥",country:"Trinidad and Tobago",number:0},
        {name:"突尼斯",country:"Tunisia",number:0},
        {name:"土耳其",country:"Turkey",number:0},
        {name:"坦桑尼亚",country:"United Republic of Tanzania",number:0},
        {name:"乌干达",country:"Uganda",number:0},
        {name:"乌克兰",country:"Ukraine",number:0},
        {name:"乌拉圭",country:"Uruguay",number:0},
        {name:"美国",country:"United States of America",number:0},
        {name:"乌兹别克斯坦",country:"Uzbekistan",number:0},
        {name:"委内瑞拉",country:"Venezuela",number:0},
        {name:"越南",country:"Vietnam",number:0},
        {name:"瓦努阿图",country:"Vanuatu",number:0},
        {name:"西岸",country:"West Bank",number:0},
        {name:"也门",country:"Yemen",number:0},
        {name:"南非",country:"South Africa",number:0},
        {name:"赞比亚",country:"Zambia",number:0},
        {name:"津巴布韦",country:"Zimbabwe",number:0},
    ];
    worldCountryCluesData.forEach(function(item,index){
        data.forEach(function(item1,index1){
            if(item.name == item1.country){
                item.number = item1.number;
            }
        });
    });
    return worldCountryCluesData;
}
